#!/usr/bin/env bash

bar() {
    # clean then deploy
    printf '\e[?25l\e[1J\e[1;%sr'
    stty -echo
    landscape
    
    printf '\e2\e[%sH\e[7;1m%*s\r%s %s\e[%sH' \
           "$LINES" \
           "$COLUMNS" "" "" \
           "$title - $artist"
}

plunger() {
    img2sixel "/tmp/abc.png" \
    -w 161 -h 156 \
    --builtin-palette=xterm256 \

    mpv --no-audio-display \
    --msg-level=all=no,statusline=debug "$@"

    # EXIT
    printf '\e[?25h'
    stty echo
}

landscape() {
    cat <<EOF
Art by Joan G. Stark

                   \       /            _\/_
                     .-'-.              //o\  _\/_
  _  ___  __  _ --_ /     \ _--_ __  __ _ | __/o\\ _
=-=-_=-=-_=-=_=-_= -=======- = =-=_=-=_,-'|"'""-|-,_ 
 =- _=-=-_=- _=-= _--=====- _=-=_-_,-"          |
jgs=- =- =-= =- = -  -===- -= - ."


EOF
}

main() {
    yes | ffmpeg -i \
    "$@" -f ffmetadata /tmp/list.txt \
    -- /tmp/abc.png \
    -loglevel quiet \

    ## file tags from /tmp/list.txt
	while IFS='=' read -r xx yy; do
                    case $xx in
                        title) title=$yy ;;
		 	artist) artist=$yy ;;
			album) album=$yy ;;
			genre) genre=$yy ;;
			date) date=$yy ;;
                    esac
                done < /tmp/list.txt

    ## pick a random file in current directory
    shuffle=$(ls | shuf -n 10 | awk 'NR==1')

    bar
    plunger "$@"
}

main "$@"

for (( ; ; )); do
     main "$shuffle"
     sleep 1
done
